# DigitalOcean App Platform Configuration
name: crypto-trading-backend
services:
- name: web
  source_dir: /
  github:
    repo: your-username/crypto_trading_system
    branch: main
  run_command: gunicorn --bind 0.0.0.0:$PORT src.main:app --timeout 120 --workers 2
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: ENVIRONMENT
    value: production
  - key: SECRET_KEY
    value: your-super-secret-key-change-this
  - key: BINANCE_API_KEY
    value: your-binance-api-key
    type: SECRET
  - key: BINANCE_SECRET_KEY
    value: your-binance-secret-key
    type: SECRET
  - key: BINANCE_TESTNET
    value: "false"
  http_port: 8080
  routes:
  - path: /
domains:
- name: your-domain.com
  type: PRIMARY
