name: whale-app-864sn
services:
- name: web
  source_dir: /
  github:
    repo: pasithde/trade_backend_python
    branch: main
  run_command: gunicorn --bind 0.0.0.0:8080 main:app
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  http_port: 8080
