name: whale-app-864sn
services:
- name: web
  source_dir: /
  github:
    repo: pasithdev/trade_backend_python
    branch: master
  run_command: gunicorn -c gunicorn.conf.py src.main:app
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  http_port: 8080
  envs:
  - key: ENVIRONMENT
    value: production
  - key: PORT
    value: "8080"
  - key: PYTHONPATH
    value: "/workspace"
  - key: GUNICORN_CMD_ARGS
    value: "--bind=0.0.0.0:8080 --workers=2 --timeout=30 --access-logfile=-"
  health_check:
    http_path: /health
    initial_delay_seconds: 20
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3